#!/usr/bin/env bash
set -euo pipefail

# runs-ai-analyzer/dev-up.sh
# Starts the shared pgvector-backed DB from jubilant-memory/config and writes
# a local .env for Spring Boot / IntelliJ.
#
# Usage: ./dev-up.sh [--reset] [--cloud] [--help]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

DB_PORT=5444
DB_NAME="runs-ai-analyzer"
CONTAINER_NAME="runs-ai-analyzer-db"
CLOUD_ENV_FILE="$SCRIPT_DIR/../consolidated-postgres/.env.cloud"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
print_status() { echo -e "${GREEN}✓${NC} $1"; }
print_error()  { echo -e "${RED}✗${NC} $1"; }
print_info()   { echo -e "${YELLOW}ℹ${NC} $1"; }

RESET_DB=false
CLOUD_MODE=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --reset) RESET_DB=true; shift ;;
    --cloud) CLOUD_MODE=true; shift ;;
    --help)  grep "^#" "$0" | head -10 | sed 's/^# \?//'; exit 0 ;;
    *)       print_error "Unknown option: $1"; exit 1 ;;
  esac
done

if ! docker ps >/dev/null 2>&1; then
  print_error "Docker is not running"
  exit 1
fi

_saved_config_user=""
_saved_config_pass=""
if [ -f ".env" ]; then
  _saved_config_user=$(grep -E "^SPRING_CLOUD_CONFIG_USERNAME=" .env | tail -1 | cut -d= -f2- || true)
  _saved_config_pass=$(grep -E "^SPRING_CLOUD_CONFIG_PASSWORD=" .env | tail -1 | cut -d= -f2- || true)
fi

if [ "$CLOUD_MODE" = true ]; then
  print_info "Configuring runs-ai-analyzer for cloud database..."

  [ -f "$CLOUD_ENV_FILE" ] || {
    print_error "Run consolidated-postgres/cloud-start.sh first — $CLOUD_ENV_FILE not found"
    exit 1
  }

  _fetch() { grep -E "^$1=" "$CLOUD_ENV_FILE" | tail -1 | cut -d= -f2-; }

  _db_url=$(_fetch "RUNS_AI_ANALYZER_DB_URL")
  _db_user=$(_fetch "RUNS_AI_ANALYZER_DB_USER")
  _db_pass=$(_fetch "RUNS_AI_ANALYZER_DB_PASSWORD")

  [ -n "$_db_url" ] || { print_error "RUNS_AI_ANALYZER_DB_URL missing in $CLOUD_ENV_FILE"; exit 1; }
  [ -n "$_db_user" ] || { print_error "RUNS_AI_ANALYZER_DB_USER missing in $CLOUD_ENV_FILE"; exit 1; }
  [ -n "$_db_pass" ] || { print_error "RUNS_AI_ANALYZER_DB_PASSWORD missing in $CLOUD_ENV_FILE"; exit 1; }

  cat > .env << EOF
# runs-ai-analyzer - cloud - generated by dev-up.sh --cloud - DO NOT COMMIT
RUNS_AI_ANALYZER_DB_URL=${_db_url}
RUNS_AI_ANALYZER_DB_USER=${_db_user}
RUNS_AI_ANALYZER_DB_PASSWORD=${_db_pass}
RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://localhost:11434}
SPRING_CLOUD_CONFIG_USERNAME=${_saved_config_user}
SPRING_CLOUD_CONFIG_PASSWORD=${_saved_config_pass}
EOF
  chmod 600 .env
  print_status "Cloud .env written"
  print_info "Run: SPRING_PROFILES_ACTIVE=prod mvn spring-boot:run"
  exit 0
fi

INFRA_DIR=""
for _candidate in \
    "$SCRIPT_DIR/../jubilant-memory/config" \
    "$HOME/IdeaProjects/jubilant-memory/config"; do
  if [ -f "$_candidate/docker-compose.yml" ]; then
    INFRA_DIR="$(cd "$_candidate" && pwd)"
    break
  fi
done

[ -n "$INFRA_DIR" ] || {
  print_error "Cannot find jubilant-memory/config"
  exit 1
}

_INFRA_ENV="$INFRA_DIR/.env"
[ -f "$_INFRA_ENV" ] || {
  print_error "Missing $_INFRA_ENV"
  print_info "Create it from template: cp $INFRA_DIR/.env.example $_INFRA_ENV"
  exit 1
}

set -a
source "$_INFRA_ENV"
set +a

_required_vars=(EVENTS_TRACKER_DB_USER EVENTS_TRACKER_DB_PASSWORD RABBITMQ_USERNAME RABBITMQ_PASSWORD)
for _v in "${_required_vars[@]}"; do
  if [ -z "${!_v:-}" ]; then
    print_error "$_v not set in $_INFRA_ENV"
    exit 1
  fi
done

if [ "$RESET_DB" = true ]; then
  print_info "Resetting ${CONTAINER_NAME}..."
  docker stop "$CONTAINER_NAME" 2>/dev/null || true
  docker rm "$CONTAINER_NAME" 2>/dev/null || true
fi

if docker ps --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
  print_status "${CONTAINER_NAME} already running on :${DB_PORT}"
else
  print_info "Starting shared pgvector database and RabbitMQ via jubilant-memory stack..."
  docker compose -f "$INFRA_DIR/docker-compose.yml" --profile running-ai up -d runs-ai-analyzer-db sathishproject-rabbitmq
fi

print_info "Waiting for PostgreSQL on :${DB_PORT}..."
_ready=false
for _i in $(seq 1 30); do
  if docker exec "$CONTAINER_NAME" pg_isready -U "$EVENTS_TRACKER_DB_USER" >/dev/null 2>&1; then
    _ready=true
    break
  fi
  sleep 1
done
[ "$_ready" = true ] || { print_error "PostgreSQL did not become ready within 30s"; exit 1; }
print_status "pgvector PostgreSQL ready on :${DB_PORT}"

_superuser=$(docker exec "$CONTAINER_NAME" printenv POSTGRES_USER 2>/dev/null || echo "postgres")
docker exec "$CONTAINER_NAME" psql -U "$_superuser" -d postgres -c \
  "DO \$\$
   BEGIN
     CREATE ROLE \"${EVENTS_TRACKER_DB_USER}\" LOGIN PASSWORD '${EVENTS_TRACKER_DB_PASSWORD}';
   EXCEPTION WHEN duplicate_object THEN NULL;
   END \$\$;" >/dev/null
docker exec "$CONTAINER_NAME" psql -U "$_superuser" -d postgres -c \
  "ALTER ROLE \"${EVENTS_TRACKER_DB_USER}\" WITH LOGIN PASSWORD '${EVENTS_TRACKER_DB_PASSWORD}';" >/dev/null
docker exec "$CONTAINER_NAME" psql -U "$_superuser" -d postgres -c \
  "GRANT ALL PRIVILEGES ON DATABASE \"${RUNS_AI_ANALYZER_DB_NAME:-$DB_NAME}\" TO \"${EVENTS_TRACKER_DB_USER}\";" >/dev/null || true

cat > .env << EOF
# runs-ai-analyzer - local - generated by dev-up.sh - DO NOT COMMIT
RUNS_AI_ANALYZER_DB_URL=jdbc:postgresql://localhost:${DB_PORT}/${RUNS_AI_ANALYZER_DB_NAME:-$DB_NAME}
RUNS_AI_ANALYZER_DB_USER=${EVENTS_TRACKER_DB_USER}
RUNS_AI_ANALYZER_DB_PASSWORD=${EVENTS_TRACKER_DB_PASSWORD}
JDBC_DATABASE_USERNAME=${EVENTS_TRACKER_DB_USER}
JDBC_DATABASE_PASSWORD=${EVENTS_TRACKER_DB_PASSWORD}
RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://localhost:11434}
SPRING_CLOUD_CONFIG_USERNAME=${_saved_config_user}
SPRING_CLOUD_CONFIG_PASSWORD=${_saved_config_pass}
EOF
chmod 600 .env

print_status ".env written (DB and RabbitMQ loaded from jubilant-memory/config/.env)"
print_info "Run: mvn spring-boot:run -Dspring-boot.run.profiles=local"
